### ISSUE TITLE
Feature request: One site is displayed twice

### ISSUE THREAD

**Issue by powerTea-cz** [Pocuston/uugle#4]
Books indexed by uuGle can be accessed via two different domains. When searching for some page using common term (expecting many results), some pages are displayed twice.

Example of duplicit urls:
- https://uuos9.plus4u.net/uu-bookkitg01-main/78462435-0238a88bac124b3ca828835b57144ffa/book/page?code=13ad141b
- https://uuapp.plus4u.net/uu-bookkit-maing01/0238a88bac124b3ca828835b57144ffa/book/page?code=13ad141b

These two results could be merged using awid and page code :)

**Comment by Pocuston** [comment]
Issue has been fixed in [release 0.0.8](https://github.com/Pocuston/uugle/releases/tag/v0.0.8)
